package tns;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-710022-redhat-00001
 * 2019-06-09T19:21:12.690+02:00
 * Generated source version: 3.1.11.fuse-710022-redhat-00001
 * 
 */
@WebService(targetNamespace = "tns", name = "BookService")
@XmlSeeAlso({ObjectFactory.class})
public interface BookService {

    @WebMethod(action = "getBooks")
    @RequestWrapper(localName = "getBooks", targetNamespace = "tns", className = "tns.GetBooks")
    @ResponseWrapper(localName = "getBooksResponse", targetNamespace = "tns", className = "tns.GetBooksResponse")
    @WebResult(name = "getBooksResult", targetNamespace = "tns")
    public tns.StringArray getBooks(
        @WebParam(name = "filter", targetNamespace = "tns")
        java.lang.String filter
    );

    @WebMethod(action = "getBookInfo")
    @RequestWrapper(localName = "getBookInfo", targetNamespace = "tns", className = "tns.GetBookInfo")
    @ResponseWrapper(localName = "getBookInfoResponse", targetNamespace = "tns", className = "tns.GetBookInfoResponse")
    @WebResult(name = "getBookInfoResult", targetNamespace = "tns")
    public tns.BookInfoResponse getBookInfo(
        @WebParam(name = "name", targetNamespace = "tns")
        java.lang.String name
    );
}
