package tns;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-710022-redhat-00001
 * 2019-06-09T19:21:12.695+02:00
 * Generated source version: 3.1.11.fuse-710022-redhat-00001
 * 
 */
@WebServiceClient(name = "BookService", 
                  wsdlLocation = "http://legacyapp-legacy.apps.prague-357d.openshiftworkshop.com/soap/books?wsdl",
                  targetNamespace = "tns") 
public class BookService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("tns", "BookService");
    public final static QName BookService = new QName("tns", "BookService");
    static {
        URL url = null;
        try {
            url = new URL("http://legacyapp-legacy.apps.prague-357d.openshiftworkshop.com/soap/books?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BookService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://legacyapp-legacy.apps.prague-357d.openshiftworkshop.com/soap/books?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BookService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BookService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BookService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BookService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BookService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BookService
     */
    @WebEndpoint(name = "BookService")
    public BookService getBookService() {
        return super.getPort(BookService, BookService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookService
     */
    @WebEndpoint(name = "BookService")
    public BookService getBookService(WebServiceFeature... features) {
        return super.getPort(BookService, BookService.class, features);
    }

}
